feat: accept multiple project ids by providing a comma separate list of ids
screendriver/gitlab-pipeline-deleter pull request #10
Opened 2020-10-09 16:08 UTC by lo1tuma

2020-10-09 17:02 UTC, screendriver requested changes

2020-10-13 13:06 UTC, lo1tuma commented on src/config.ts
> +  return parseInt(value.trim(), 10);
Cool

2020-10-13 13:06 UTC, lo1tuma commented on src/config.ts
> +function commaSeparatedStringToNumberArray(commaSeparatedString: string): number[] {
done

2020-10-13 13:07 UTC, lo1tuma commented on src/App.tsx
> +  projectIds: number[];
done

2020-10-13 13:07 UTC, lo1tuma commented on src/config.ts
> +  projectIds: z.array(z.number()).nonempty(),
Done

2020-10-13 13:33 UTC, screendriver approved these changes
GNTM 👠

2020-10-13 14:44 UTC, screendriver approved these changes

2020-10-13 14:44 UTC, merged